server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React router — renvoie index.html pour toutes les routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend FastAPI
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }
}
